### PR TITLE
Fix debug build

### LINKED ISSUE #412: Control reaches end of non-void function when building in debug mode
When compiling with `CMAKE_BUILD_TYPE=Debug` (yikes, yes, I know), I get the following error:

```
catkin_ws/src/cartographer/cartographer/io/hybrid_grid_points_processor.cc:64:1: 
error: control reaches end of non-void function [-Werror=return-type]
```

I have no idea why building regularly (with `CMAKE_BUILD_TYPE=Release`) doesn't trigger this.

### PR DESCRIPTION
**Pull request by ojura**
Add a fake return value after LOG(FATAL) in
HybridGridPointsProcessor::Flush(). This keeps gcc versions lower
than 7 happy when building without optimisation (i.e. debug build).
Fixes #412.

### CODE REVIEW

File: cartographer/io/hybrid_grid_points_processor.cc [hunk 1]
```diff
@@ -61,6 +61,7 @@ PointsProcessor::FlushResult HybridGridPointsProcessor::Flush() {
       return FlushResult::kFinished;
   }
   LOG(FATAL) << "Failed to receive FlushResult::kFinished";
+  return FlushResult::kFinished;
```
Comment (SirVer) [inline cartographer/io/hybrid_grid_points_processor.cc]: Please add a comment to the GCC bug report why this should not be removed.

Comment (ojura) [inline cartographer/io/hybrid_grid_points_processor.cc]: Done.
