### PR TITLE
CMake bug fixes and performance improvements.

### LINKED ISSUE #341: Dockerfiles install Ceres from master instead of a specific version

### LINKED ISSUE #629: FindLuaGoogle.cmake accepts Lua 5.1 though cartographer requires >= 5.2

### PR DESCRIPTION
**Pull request by SirVer**
- Pin versions of Ceres and protobuf (Fixes #341).
- Require Lua >= 5.2 (Fixes #629).
- No longer run ceres tests in CI. We implicitly test Ceres through Cartographer's tests and this saves ~4 minutes on CI.

### CODE REVIEW

**Comment by ojura** [comment]
> - No longer run ceres tests in CI. We implicitly test Ceres through Cartographer's tests and this saves ~4 minutes on CI.
Wait, where has this been changed in this PR?

File: scripts/install_ceres.sh [hunk 1]
```diff
@@ -17,9 +17,12 @@
 set -o errexit
 set -o verbose
 
+VERSION="1.13.0"
+
 # Build and install Ceres.
 git clone https://ceres-solver.googlesource.com/ceres-solver
 cd ceres-solver
+git checkout tags/${VERSION}
```
Comment (damienrg) [inline scripts/install_ceres.sh]: Clone directly the tag to save time if they are huge differences from master and tag?

Comment (damienrg) [inline scripts/install_ceres.sh]: Clone directly the tag to save time if they are huge differences from master and tag?

File: scripts/install_proto3.sh [hunk 2]
```diff
@@ -17,9 +17,12 @@
 set -o errexit
 set -o verbose
 
+VERSION="v3.4.1"
+
 # Build and install proto3.
 git clone https://github.com/google/protobuf.git
 cd protobuf
+git checkout tags/${VERSION}
```
Comment (damienrg) [inline scripts/install_proto3.sh]: Same here.

File: scripts/install_ceres.sh (hunk 1 above)
Comment (SirVer) [reply scripts/install_ceres.sh]: The only way to do this I know is to use `git clone --branch` which also accepts tags. But if there is a tag and a branch with the same name, this will give us the wrong thing, so I had to use this. 

https://stackoverflow.com/questions/791959/download-a-specific-tag-with-git

**Comment by SirVer** [comment]
@ojura Ups, thanks for catching this merge-o.

@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

File: scripts/install_ceres.sh (hunk 1 above)
Comment (damienrg) [reply scripts/install_ceres.sh]: Yes I was thinking to `git clone --branch` and indeed it does not work in this case.

Comment (damienrg) [reply scripts/install_ceres.sh]: Using git fetch you can do something like this:
```
mkdir ceres-solver
cd ceres-solver
git init
git remote add origin https://ceres-solver.googlesource.com/ceres-solver
git fetch --depth 1 origin "tags/${VERSION}"
git checkout -b "${VERSION}" FETCH_HEAD
```

Comment (SirVer) [reply scripts/install_ceres.sh]: @damienrg With the short history of Cartographer, this barely saves space. I think this is not worth the extra lines for now.
