### PR TITLE
Check imu_data array size before access

### LINKED ISSUE #390: Trimmer crashes
As @Mofef mentioned in #389, the latest code crashes while trimming submaps. Here is the error log.

```
[/cartographer_offline_node  INFO 1499262071.746585000, 1495552307.184251417]: I0705 15:41:11.000000 14339 constraint_builder.cc:245] Node (0, 157) with 103 points on submap (0, 4) differs by translation 0.00 rotation 0.001 with score 62.4%.
[/cartographer_offline_node  INFO 1499262071.746623421, 1495552307.184251417]: I0705 15:41:11.000000 14339 constraint_builder.cc:266] 22 computations resulted in 22 additional constraints.
[/cartographer_offline_node  INFO 1499262071.746768683, 1495552307.184251417]: I0705 15:41:11.000000 14339 constraint_builder.cc:268] Score histogram:
Count: 24  Min: 0.465051  Max: 0.696167  Mean: 0.563143
[0.465051, 0.488163)	                  ##	Count: 2 (8.333333%)	Total: 2 (8.333333%)
[0.488163, 0.511274)	                  ##	Count: 2 (8.333333%)	Total: 4 (16.666666%)
[0.511274, 0.534386)	                 ###	Count: 4 (16.666666%)	Total: 8 (33.333332%)
[0.534386, 0.557497)	                 ###	Count: 3 (12.500000%)	Total: 11 (45.833332%)
[0.557497, 0.580609)	                ####	Count: 5 (20.833334%)	Total: 16 (66.666664%)
[0.580609, 0.603721)	                 ###	Count: 3 (12.500000%)	Total: 19 (79.166664%)
[0.603721, 0.626832)	                   #	Count: 1 (4.166667%)	Total: 20 (83.333336%)
[0.626832, 0.649944)	                  ##	Count: 2 (8.333333%)	Total: 22 (91.666664%)
[0.649944, 0.673056)	                   #	Count: 1 (4.166667%)	Total: 23 (95.833336%)
[0.673056, 0.696167]	                   #	Count: 1 (4.166667%)	Total: 24 (100.000000%)
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
[cartographer_offline_node-3] process has died [pid 14314, exit code -6, cmd /home/jihoonl/work/ros/localization/install/lib/cartographer_ros/cartographer_offline_node -configuration_directory /home/jihoonl/work/ros/simws/src/toru_rosbag_play/config/cartographer -configuration_basename toru.lua -bag_filenames /home/jihoonl/work/rosbag/test.bag -urdf_filename /home/jihoonl/work/ros/simws/src/toru_rosbag_play/config/urdf/toru_for_carto.xacro scan:=/scan_aggregated __name:=cartographer_offline_node __log:=/home/jihoonl/.ros/log/97b6dd52-6187-11e7-8208-28d2442d0551/cartographer_offline_node-3.log].
log file: /home/jihoonl/.ros/log/97b6dd52-6187-11e7-8208-28d2442d0551/cartographer_offline_node-3*.log
```

And I have quickly confirmed that it is not crashing in the version 7f4f78e4513d583b4a1a90f76014db26871cf49e. So, I assume that one of refactoring work within two weeks broke the trimming process.

### PR DESCRIPTION
**Pull request by jihoonl**
To resolve #390.

### CODE REVIEW

File: cartographer/mapping_2d/sparse_pose_graph/optimization_problem.cc [hunk 1]
```diff
@@ -89,10 +89,12 @@ void OptimizationProblem::TrimTrajectoryNode(const mapping::NodeId& node_id) {
   CHECK_EQ(trajectory_data.num_trimmed_nodes, node_id.node_index);
   auto& node_data = node_data_.at(node_id.trajectory_id);
   CHECK(!node_data.empty());
-  const common::Time node_time = node_data.front().time;
-  auto& imu_data = imu_data_.at(node_id.trajectory_id);
-  while (imu_data.size() > 1 && imu_data[1].time <= node_time) {
-    imu_data.pop_front();
+  if(imu_data_.size() > static_cast<size_t>(node_id.trajectory_id)) {
```
Comment (wohe) [inline cartographer/mapping_2d/sparse_pose_graph/optimization_problem.cc]: Consistency with similar checks in other places: `node_id.trajectory_id < static_cast<int>(imu_data_.size())`?

Comment (jihoonl) [inline cartographer/mapping_2d/sparse_pose_graph/optimization_problem.cc]: That change gives `warning: comparison between signed and unsigned integer expressions`.

You meant `static_cast<size_t>(node_id.trajectory_id) < imu_data_.size()` ?

Comment (jihoonl) [inline cartographer/mapping_2d/sparse_pose_graph/optimization_problem.cc]: ah nevermind. I misread
